package:
  name: flightdata
  version: "0.0.1"

build:
  number: 0

source:
  path: ./

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - numpy
    - pandas
    - ardupilot_log_reader
    - pint
  run:
    - python
    - numpy
    - pandas
    - ardupilot_log_reader
    - pint
test:
  imports:
    - flightdata